testing

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -23,18 +23,10 @@ jobs:
       run: |
         pip install -r requirements.txt || true
 
-    - name: Run Options_in_future_date.py script
-      run: | 
-        python Options_in_future_date.py
 
     - name: Run Politicians_trades.py script
       run: |
         python Politicians_trades.py
-
-    - name: List files after running scripts
-      run: |
-        ls -al
-        ls -al | grep '.csv'
 
     - name: Configure Git to use GitHub token
       run: |
@@ -45,7 +37,7 @@ jobs:
 
     - name: Commit CSV files
       run: |
-        git add top_100_stock_and_options_data.csv politicians_trades.csv || echo "One or both files are missing!"
+        git add politicians_trades.csv || echo "One or both files are missing!"
         git commit -m "Update CSV files"
         git push origin HEAD:${{ github.ref }}
       env:
